language: generic
services:
- docker
script:
- docker build -t danigatunes/autocalamari .
# deploy:
#   on:
#     branch: master
#   provider: script
#   script: echo ${DOCKER_PASSWORD} | docker login -u danigatunes --password-stdin && docker push danigatunes/autocalamari  
#   skip_cleanup: true
